{'id': 1, 'full_name': 'Finance', 'four_letter_code': 'FNCE', 'faculty_url': 'https://fnce.wharton.upenn.edu/faculty/faculty-list/', 'staff_url': 'https://fnce.wharton.upenn.edu/department-information/staff/', 'phd_url': 'https://fnce.wharton.upenn.edu/programs/phd/meet-our-phd-students/'}
{'id': 2, 'full_name': 'Accounting', 'four_letter_code': 'ACCT', 'faculty_url': 'https://accounting.wharton.upenn.edu/faculty/faculty-list/', 'staff_url': 'https://accounting.wharton.upenn.edu/department-information/staff/', 'phd_url': 'https://accounting.wharton.upenn.edu/programs/phd/current-students/'}
{'id': 3, 'full_name': 'Business Economics and Public Policy', 'four_letter_code': 'BEPP', 'faculty_url': 'https://bepp.wharton.upenn.edu/faculty/faculty-list/', 'staff_url': 'https://bepp.wharton.upenn.edu/department-information/staff/', 'phd_url': 'https://bepp.wharton.upenn.edu/programs/phd/current-students/'}
{'id': 4, 'full_name': 'Health Care Management', 'four_letter_code': 'HCMG', 'faculty_url': 'https://hcmg.wharton.upenn.edu/faculty/faculty-list/', 'staff_url': 'https://hcmg.wharton.upenn.edu/department-information/staff/', 'phd_url': 'https://hcmg.wharton.upenn.edu/programs/phd/students-graduates/'}
{'id': 5, 'full_name': 'Legal Studies and Business Ethics', 'four_letter_code': 'LGST', 'faculty_url': 'https://lgst.wharton.upenn.edu/faculty/faculty-list/', 'staff_url': 'https://lgst.wharton.upenn.edu/department-information/staff/', 'phd_url': 'https://lgst.wharton.upenn.edu/programs/phd/students/'}
{'id': 6, 'full_name': 'Management', 'four_letter_code': 'MGMT', 'faculty_url': 'https://mgmt.wharton.upenn.edu/faculty-list/', 'staff_url': 'https://mgmt.wharton.upenn.edu/staff-list/', 'phd_url': 'https://mgmt.wharton.upenn.edu/programs/phd/current-students/'}
{'id': 7, 'full_name': 'Marketing', 'four_letter_code': 'MKTG', 'faculty_url': 'https://marketing.wharton.upenn.edu/faculty/faculty-list/', 'staff_url': 'https://marketing.wharton.upenn.edu/contact-us/staff/', 'phd_url': 'https://marketing.wharton.upenn.edu/contact-us/phdstudentscontact/'}
{'id': 8, 'full_name': 'Operations, Information and Decisions', 'four_letter_code': 'OIDD', 'faculty_url': 'https://oid.wharton.upenn.edu/faculty/faculty-list/', 'staff_url': 'https://oid.wharton.upenn.edu/department-information/staff/', 'phd_url': 'https://oid.wharton.upenn.edu/programs/phd/students/'}
{'id': 9, 'full_name': 'Real Estate', 'four_letter_code': 'REAL', 'faculty_url': 'https://real-estate.wharton.upenn.edu/faculty/faculty-list/', 'staff_url': 'https://real-estate.wharton.upenn.edu/department-information/staff/', 'phd_url': 'https://bepp.wharton.upenn.edu/programs/applied-economics-job-market-candidates/'}
{'id': 10, 'full_name': 'Statistics and Data Science', 'four_letter_code': 'STAT', 'faculty_url': 'https://statistics.wharton.upenn.edu/faculty/faculty-list/', 'staff_url': 'https://statistics.wharton.upenn.edu/department-information/administrative-staff/', 'phd_url': 'https://statistics.wharton.upenn.edu/programs/phd/students/'}