# Generated by Django 4.1.7 on 2023-04-02 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('four_letter_code', models.CharField(max_length=4, verbose_name='Four Letter Code')),
                ('faculty_url', models.URLField()),
                ('staff_url', models.URLField()),
                ('phd_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
        migrations.AddField(
            model_name='page',
            name='pages',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.pages'),
        ),
    ]
